"use client"
import { useState } from "react"
import { CheckCircle2, CircleAlert, LoaderCircle, LockKeyhole } from "lucide-react"
type View={name:string; badge:string; tone:"ok"|"alert"|"wait"; odds:string; button:string; message:string; detail:string; icon:typeof CheckCircle2}
const views:View[]=[
  {name:"正常确认",badge:"可确认",tone:"ok",odds:"2.10",button:"确认投注",message:"选项、盘口、赔率和金额在同一张投注单中可见。",detail:"用户确认前能知道本次提交采用的具体报价。",icon:CheckCircle2},
  {name:"赔率变化",badge:"需要确认",tone:"alert",odds:"2.20",button:"按新赔率确认",message:"报价变化后，突出新赔率并说明需要重新确认。",detail:"不要让价格悄悄变化；旧值与新值应能被用户区分。",icon:CircleAlert},
  {name:"选项封盘",badge:"暂不可投注",tone:"alert",odds:"封盘",button:"当前不可确认",message:"选项不可用时，保留赛事与玩法信息，并说明当前状态。",detail:"不可用不等于页面消失；用户需要知道发生了什么。",icon:LockKeyhole},
  {name:"提交处理中",badge:"处理中",tone:"wait",odds:"2.10",button:"正在确认…",message:"提交后锁定重复操作，并提示用户等待结果查询。",detail:"处理中不能直接写成失败，也不应允许反复点击产生重复请求。",icon:LoaderCircle},
]
const tone={ok:"border-emerald-200 bg-emerald-50 text-emerald-700",alert:"border-amber-200 bg-amber-50 text-amber-700",wait:"border-sky-200 bg-sky-50 text-sky-700"}
export function SportsDesignExperienceDemo(){const[index,setIndex]=useState(0);const v=views[index];const Icon=v.icon;return <section className="mt-6 overflow-hidden rounded-lg border border-line bg-white shadow-sm" aria-labelledby="design-demo-title"><div className="p-5 md:p-8"><div className="flex flex-wrap items-center gap-3"><h2 id="design-demo-title" className="text-xl font-semibold text-ink">一张投注单，怎样让状态一眼看懂？</h2><span className="rounded-md bg-paper px-2 py-1 text-xs text-muted">界面状态 · 设计示意</span></div><p className="mt-3 text-sm leading-7 text-muted">切换状态，查看赔率、主操作和解释文案怎样同时变化。</p><div className="mt-5 flex flex-wrap gap-2" role="group" aria-label="选择设计状态">{views.map((x,i)=><button key={x.name} type="button" aria-pressed={index===i} onClick={()=>setIndex(i)} className={`rounded-md border px-3 py-2.5 text-sm font-medium ${index===i?"border-brand-600 bg-brand-50 text-brand-700":"border-line text-muted hover:bg-paper"}`}>{x.name}</button>)}</div></div><div className="grid border-t border-line lg:grid-cols-[.85fr_1.15fr]"><div className="bg-paper p-5 md:p-8"><div className="mx-auto max-w-sm rounded-xl border border-line bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><p className="text-xs text-muted">英超 · 全场独赢</p><p className="mt-1 font-semibold text-ink">海港队 vs 山城队</p></div><span className={`h-fit rounded-md border px-2 py-1 text-xs font-semibold ${tone[v.tone]}`}>{v.badge}</span></div><div className="mt-5 rounded-lg border border-line p-4"><p className="text-xs text-muted">主胜</p><p className="mt-1 text-2xl font-semibold text-ink">{v.odds}</p></div><div className="mt-4 flex justify-between text-sm"><span className="text-muted">投注金额</span><strong className="text-ink">100</strong></div><button type="button" disabled={v.tone!=="ok"} className="mt-5 w-full rounded-md bg-brand-700 px-4 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-slate-400">{v.button}</button></div></div><div className="p-5 md:p-8" aria-live="polite"><p className="text-xs font-semibold text-brand-700">当前状态 · {v.badge}</p><h3 className="mt-2 text-2xl font-semibold text-ink">{v.name}</h3><div className="mt-5 rounded-lg border border-line p-4"><p className="inline-flex items-center gap-2 text-sm font-semibold text-ink"><Icon className="h-4 w-4 text-brand-700" aria-hidden="true" />界面应说明什么</p><p className="mt-2 text-sm leading-7 text-muted">{v.message}</p></div><p className="mt-4 border-l-2 border-brand-600 pl-4 text-sm leading-7 text-muted">评审重点：{v.detail}</p></div></div></section>}
