"use client"
import { useState } from "react"
import { CheckCircle2, Clock3, MessageCircleQuestion, RotateCcw, ShieldAlert } from "lucide-react"
type Case = { name:string; status:string; tone:"ok"|"wait"|"alert"; user:string; agent:string; records:string[]; rule:string; icon:typeof CheckCircle2 }
const cases: Case[] = [
  { name:"已受理待结算", status:"待结算", tone:"wait", user:"比赛已结束，为什么余额还没变化？", agent:"注单已受理，当前等待赛果确认。赛果确认后会按受理时的玩法与赔率结算。", records:["注单：BET-2026-018，已受理","赛果：已完场，等待确认版本","钱包：暂未生成派奖流水"], rule:"完场与赛果确认是两个状态；确认前不提前派奖。", icon:Clock3 },
  { name:"报价变化未受理", status:"未受理", tone:"alert", user:"我点击确认了，为什么没有生成注单？", agent:"提交时当前报价已变化，页面需要重新确认。未生成受理记录时，钱包不会扣款或派奖。", records:["请求：报价版本不一致","注单：未创建","钱包：无资金流水"], rule:"报价变化后，必须以用户重新确认的当前报价处理。", icon:RotateCcw },
  { name:"提交进入复核", status:"复核中", tone:"wait", user:"为什么我的提交一直显示处理中？", agent:"本次提交正在复核，结果确认前请不要重复提交。客服可查询请求标识与当前处理状态。", records:["请求：REQ-4102，复核中","注单：等待处理结论","钱包：无最终资金动作"], rule:"复核中不是失败；页面应避免给出错误结论或让用户重复提交。", icon:ShieldAlert },
  { name:"已结算已到账", status:"已结算", tone:"ok", user:"我在哪里确认这次结算结果？", agent:"注单详情会显示结算结果与资金流水；钱包记录可以查看对应的到账金额和时间。", records:["注单：主胜，赔率 2.10","赛果：2 : 0，版本 R-18","钱包：PAY-1024，+210"], rule:"客服应能通过注单标识关联赛果依据和唯一资金流水。", icon:CheckCircle2 },
]
const tone={ok:"border-emerald-200 bg-emerald-50 text-emerald-700",wait:"border-sky-200 bg-sky-50 text-sky-700",alert:"border-amber-200 bg-amber-50 text-amber-700"}
export function SportsServiceRulesDemo(){const[index,setIndex]=useState(0);const item=cases[index];const Icon=item.icon;return <section className="mt-6 overflow-hidden rounded-lg border border-line bg-white shadow-sm" aria-labelledby="service-demo-title"><div className="p-5 md:p-8"><div className="flex flex-wrap items-center gap-3"><h2 id="service-demo-title" className="text-xl font-semibold text-ink">客服查一张注单，先看什么？</h2><span className="rounded-md bg-paper px-2 py-1 text-xs text-muted">虚构查单 · 规则说明</span></div><p className="mt-3 text-sm leading-7 text-muted">选择用户问题，查看适合的解释方式，以及客服需要核对的记录。</p><div className="mt-5 flex flex-wrap gap-2" role="group" aria-label="选择客服场景">{cases.map((next,i)=><button key={next.name} type="button" aria-pressed={index===i} onClick={()=>setIndex(i)} className={`rounded-md border px-3 py-2.5 text-sm font-medium ${index===i?"border-brand-600 bg-brand-50 text-brand-700":"border-line text-muted hover:bg-paper"}`}>{next.name}</button>)}</div></div><div className="grid border-t border-line lg:grid-cols-[.85fr_1.15fr]"><div className="bg-paper p-5 md:p-8"><div className="rounded-lg border border-line bg-white p-5"><div className="flex items-center justify-between gap-3"><span className="inline-flex items-center gap-2 font-semibold text-ink"><Icon className="h-5 w-5 text-brand-700" aria-hidden="true" />BET-2026-018</span><span className={`rounded-md border px-2 py-1 text-xs font-semibold ${tone[item.tone]}`}>{item.status}</span></div><p className="mt-5 text-xs font-semibold text-muted">客服核对</p><ul className="mt-3 space-y-3 text-sm leading-6 text-ink">{item.records.map(x=><li key={x} className="rounded-md border border-line p-3">{x}</li>)}</ul></div></div><div className="p-5 md:p-8" aria-live="polite"><p className="inline-flex items-center gap-2 text-xs font-semibold text-brand-700"><MessageCircleQuestion className="h-4 w-4" aria-hidden="true" />用户问题</p><h3 className="mt-2 text-xl font-semibold text-ink">{item.user}</h3><div className="mt-5 rounded-lg border border-line p-4"><p className="text-sm font-semibold text-ink">建议说明</p><p className="mt-2 text-sm leading-7 text-muted">{item.agent}</p></div><p className="mt-4 border-l-2 border-brand-600 pl-4 text-sm leading-7 text-muted">规则要点：{item.rule}</p></div></div></section>}
