"use client"
import { useState } from "react"
import { ArrowRight, CheckCircle2, Database, ReceiptText, Rss, Trophy } from "lucide-react"
const steps=[
  {name:"赛事事件",title:"数据源推送比分与状态",detail:"事件带有赛事标识、发生时间与版本；系统先检查是否重复或乱序。",icon:Rss},
  {name:"行情更新",title:"更新当前可展示的赔率",detail:"行情服务按赛事、玩法、选项更新当前报价；不可用状态同样需要推送。",icon:Database},
  {name:"受理注单",title:"保存受理时的成交快照",detail:"提交请求使用唯一标识；受理成功后保存玩法、赔率、金额和报价版本。",icon:ReceiptText},
  {name:"确认结算",title:"按确认赛果处理资金",detail:"赛果确认后才生成结算指令；重复回调不能重复改变余额。",icon:Trophy},
]
export function SportsIntegrationDemo(){const[index,setIndex]=useState(0);const s=steps[index];const Icon=s.icon;return <section className="mt-6 overflow-hidden rounded-lg border border-line bg-white shadow-sm" aria-labelledby="integration-demo-title"><div className="p-5 md:p-8"><div className="flex flex-wrap items-center gap-3"><h2 id="integration-demo-title" className="text-xl font-semibold text-ink">一条体育数据，怎样走到结算？</h2><span className="rounded-md bg-paper px-2 py-1 text-xs text-muted">接口链路 · 简化示意</span></div><p className="mt-3 text-sm leading-7 text-muted">按顺序选择链路节点，理解每一步要保存什么、校验什么。</p><div className="mt-5 flex flex-wrap items-center gap-2" role="group" aria-label="选择技术接入步骤">{steps.map((x,i)=><button key={x.name} type="button" aria-pressed={index===i} onClick={()=>setIndex(i)} className={`rounded-md border px-3 py-2.5 text-sm font-medium ${index===i?"border-brand-600 bg-brand-50 text-brand-700":"border-line text-muted hover:bg-paper"}`}>{i+1}. {x.name}</button>)}</div></div><div className="grid border-t border-line lg:grid-cols-[.85fr_1.15fr]"><div className="bg-paper p-5 md:p-8"><div className="space-y-3">{steps.map((x,i)=>{const X=x.icon;return <div key={x.name} className={`flex items-center gap-3 rounded-lg border p-3 ${i===index?"border-brand-200 bg-brand-50":"border-line bg-white"}`}><X className="h-4 w-4 text-brand-700" aria-hidden="true"/><span className="text-sm font-medium text-ink">{x.name}</span>{i<steps.length-1&&<ArrowRight className="ml-auto h-4 w-4 text-muted" aria-hidden="true"/>}</div>})}</div></div><div className="p-5 md:p-8" aria-live="polite"><p className="text-xs font-semibold text-brand-700">第 {index+1} 步 · {s.name}</p><div className="mt-4 flex items-start gap-3"><div className="rounded-lg bg-brand-50 p-3"><Icon className="h-6 w-6 text-brand-700" aria-hidden="true"/></div><div><h3 className="text-2xl font-semibold text-ink">{s.title}</h3><p className="mt-3 text-sm leading-7 text-muted">{s.detail}</p></div></div><p className="mt-6 border-l-2 border-brand-600 pl-4 text-sm leading-7 text-muted"><CheckCircle2 className="mr-2 inline h-4 w-4 text-brand-700" aria-hidden="true"/>关键原则：每个外部事件和资金动作都要可追溯、可去重，并保留对应版本。</p></div></div></section>}
